server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=pharaoh
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    initialization-mode: always

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true